### ISSUE TITLE
ToDo list for submission to JOSE

### ISSUE THREAD

**Issue by fwitte** [fwitte/TESPy_teaching_exergy#1]
# All pages

- [x] #4

# Introductory pages

- [ ] #5

## Getting Started

- [ ] #6
 
## Introduction

- [ ] #7
- [ ] #8
- [ ] Complete Engineering Thermodynamics section (optional, might be removed for now)
- [ ] #2

# Tutorial sections

## General

- [ ] Add learning objectives and short scope (5 - 10 keywords at top of each page)
- [ ] Add lessons learned
- [ ] Ensure consistency in figures and usage of dropdowns (optional)
- [ ] Ensure consistency in coding style (optional)
- [ ] Make a beautiful landing pages for all sections (optional)

## Single Component Systems 

- [ ] Double check heat exchanger plots
- [ ] Explanations for heat exchanger results are missing
- [ ] Some figures in the compressor system are missing/not working

## Simple Processes

- [ ] #9
- [ ] #10
- [ ] Clausius Rankine cycle setup must be changed for analysis of ambient temperature influence
- [ ] Clausius Rankine cycle missing analysis for topological improvements
- [ ] Heat pump ambient temperature etc.
- [ ] Heat pump evaporator dissipative?
- [ ] Heat pump cycle missing analysis for topological improvements

## Complex Processes

- [ ] #3
